// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: application.sql

package db

import (
	"context"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
  name,
  source_text
) VALUES (
  $1, $2
)
RETURNING id, name, source_text, created_at
`

type CreateApplicationParams struct {
	Name       string `json:"name"`
	SourceText string `json:"source_text"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplication, arg.Name, arg.SourceText)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceText,
		&i.CreatedAt,
	)
	return i, err
}
