// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Application struct {
	ID         int32     `json:"id"`
	Name       string    `json:"name"`
	SourceText string    `json:"source_text"`
	CreatedAt  time.Time `json:"created_at"`
}

type SourceUnit struct {
	ID                int32          `json:"id"`
	ApplicationID     int32          `json:"application_id"`
	TranslationUnitID int32          `json:"translation_unit_id"`
	Text              sql.NullString `json:"text"`
}

type TranslationUnit struct {
	ID            int32          `json:"id"`
	ApplicationID int32          `json:"application_id"`
	SourceUnitID  int32          `json:"source_unit_id"`
	Text          sql.NullString `json:"text"`
}
